import './globals.css';
import AuthProvider from '@/components/authProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full pt-14">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
